lint:
  files_exist:
    - conf/igenomes.config
  multiqc_config:
    - report_comment
  files_unchanged:
    - .gitignore
    - .github/PULL_REQUEST_TEMPLATE.md
  nextflow_config:
    - config_defaults:
        - params.miairr
        - params.report_rmd
        - params.report_css
        - params.report_logo
        - params.report_logo_img
        - params.config_profile_url
nf_core_version: 3.5.1
repository_type: pipeline
template:
  author: Gisela Gabernet, Susanna Marquez, Alexander Peltzer, Simon Heumos
  description: B and T cell repertoire analysis pipeline with the Immcantation framework.
  force: false
  is_nfcore: true
  name: airrflow
  org: nf-core
  outdir: .
  version: "5.0.0"
