lint:
  files_exist:
    - conf/igenomes.config
  multiqc_config:
    - report_comment
  nextflow_config:
    - params.miairr
    - params.report_rmd
    - params.report_css
    - params.report_logo
    - params.report_logo_img
    - params.config_profile_url
repository_type: pipeline
