nextflow run nf-core/airrflow -r 4.4.0 \
-profile singularity \
--mode fastq \
--input subset_metadata_pcr_umi_airr_300.tsv \
--cprimers 's3://ngi-igenomes/test-data/airrflow/pcr_umi/cprimers.fasta' \
--vprimers 's3://ngi-igenomes/test-data/airrflow/pcr_umi/vprimers.fasta' \
--library_generation_method specific_pcr_umi \
--cprimer_position R1 \
--umi_length 15 \
--umi_start 0 \
--umi_position R1 \
--clonal_threshold 0.1 \
-c resource.config \
--outdir bulk_fastq_results \
-resume
